### PR TITLE
Micro Reddit is a cloned version of Reddit replicated using Ruby on Rails 

### PR DESCRIPTION
**Pull request by Mihndim2020**
- We created three models; user, post, and comment,
- We implemented associations and validations, 
- We created the various migrations.

### CODE REVIEW

**Comment by Mihndim2020** [comment]
The Ruby version we used for this project is 3.0.0. The Microverse version of Rubocop is outdated and does not handle Ruby 3.0.0. Please tell us what to do about that. Thank you.

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello, team @Mihndim2020 and @VanessaAoki 👋🏾 👋🏾 . Congratulations on making it this far in this project 🥳 

### Highlights

- [x] Your README file is well written
- [x] Your PR description is on point too 🥂 
- [x] Your project works well ✔️ 

### To Improve
#### General
- [x] I have noted your comment on linters not being able to handle Ruby v 3.0.0. We really apologize for this and thank you for making us aware of the problem, I will raise the issue with Student Success for further investigations. In the meantime, you could install a lower version on Ruby say 2.7.0 or 2.7.2, then run rubocop using these versions. I know it's a lot of work but its a learning process 😄 
- [x] For stylelint, it seems you didn't do a proper configuration that's why it's failing. Kindly [check this link on how to setup stylelint](https://github.com/microverseinc/linters-config/tree/master/ror)

#### Project Specific

- [x] In the user model, change the following relationships to :-  `has_many :posts` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_posts.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)) and  `has_many :comments`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] In the post model change this relationship from `has_many: comment` to `has_many :comments`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
- [x] Since this is a console project, you could provide the user with the commands on how to create users, posts as well as comments, and the fields required in the README file. A simple screenshot or gif might do the trick 😄 

That's all :smile: kindly submit another review when done.

_If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me @mimipeshy. I will be happy to help_
Regards
Peris Ndanu

**Comment by VanessaAoki** [comment]
@mimipeshy good afternoon,

First of all, I would like to thank you for the review, we are working hard to make all the required changes, but we got stuck and can't seem to figure out what's the issue:

- when we changed the post model relationship from has_many: comment to has_many :comments it stopped working! We tried to redo a lot of the associations, but not seems to work, can you help us?
Everything was working fine before that change!

Once again, thank you.

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: INVALID PULL REQUEST :red_circle: 

## Hello team, the reason why I am invalidating this pull request is because this project was requested as `Associations` project whereas this project is the `Micro-reddit/Building with Active Record ` project. Please request another code review for the correct project

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

HAPPY CODING :computer: :desktop_computer:

**Review by enaburekhan — APPROVED** [review]
# Status: Approve:heavy_check_mark:
**Hi team!
Congratulations:clap::clap:. Thank you for implementing all the changes requested by the last reviewer:pray:.** **You can go ahead and merge the PR**. 

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Pull request merged**
